#a=10
b=20
print(type(b))
c=3.21
print(type(c))
a=int(input("enter the first"))
b=int(input("enter the second "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)
print(a++b)
print(a--b)
print(a+-b)
print(a==b)
print(a!=b)
print(a<b)
print(a>b)
print(a<=b)
print(a>=b)
print(a%b)
print(a>b and b>a)
print(a<b or b<a)
print(b>a and a>b)
print(not(a>b and b>a))
print(a&b)
print(a|b)
print(a^b)
print(a<<b)
print(a>>b)